import { ArrowRight, Headphones, Radio, Search as SearchIcon, Sparkles, Waves, Heart, MessageCircle, Share2 } from 'lucide-react';
import { type FormEvent, useState } from 'react';
import { Link, useLocation } from 'wouter';
import { artists, moods, tracks } from '@/data/mockMusic';
import { creators } from '@/data/creators';
import { PageHeader, TrackCard, TrackRow, useSado } from '@/components/sado-shell';

export default function Home() {
  const { t, playTrack } = useSado();
  const [followed, setFollowed] = useState<string[]>(() => { try { return JSON.parse(localStorage.getItem('sado-followed-creators') || '[]'); } catch { return []; } });
  const toggleFollow = (id: string) => setFollowed((ids) => { const next = ids.includes(id) ? ids.filter((x) => x !== id) : [...ids, id]; localStorage.setItem('sado-followed-creators', JSON.stringify(next)); return next; });
  const [, setLocation] = useLocation();
  const [query, setQuery] = useState('');
  const submitSearch = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setLocation(query.trim() ? `/search?query=${encodeURIComponent(query.trim())}` : '/search');
  };
  return <div className="mx-auto max-w-[1500px]">
    <PageHeader eyebrow="SADO / 01" title={`${t.greeting} ${t.name}`} description={t.subtitle} />
    <div className="space-y-12 px-5 sm:px-8 lg:px-12">
      <section className="sado-enter-delay relative overflow-hidden rounded-[28px] border border-border bg-card px-6 py-8 sm:px-10 sm:py-10">
         <div className="absolute -right-20 -top-28 h-72 w-72 rounded-full bg-primary/10 blur-3xl" /><div className="relative max-w-2xl"><p className="mb-5 font-mono-ui text-[10px] uppercase tracking-[.2em] text-primary">{t.heroEyebrow}</p><h2 className="max-w-xl text-4xl font-extrabold leading-[1.04] tracking-[-.05em]">{t.heroTitleLead} <span className="font-display font-normal italic text-primary">{t.heroTitleAccent}</span> {t.heroTitleTail}</h2><p className="mt-5 max-w-md text-sm leading-6 text-muted-foreground">{t.heroDescription}</p><form onSubmit={submitSearch} className="mt-7 flex max-w-lg items-center gap-2 rounded-2xl border border-border bg-background/45 px-3 py-2 focus-within:border-primary/60"><SearchIcon size={17} className="shrink-0 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t.searchPlaceholder} aria-label={t.searchTitle} data-testid="input-home-search" className="h-10 min-w-0 flex-1 bg-transparent px-1 text-sm outline-none placeholder:text-muted-foreground" /><button type="submit" data-testid="button-home-search" className="flex shrink-0 items-center gap-1 rounded-xl bg-primary px-3 py-2.5 text-xs font-extrabold text-primary-foreground transition hover:brightness-110">{t.heroCta}<ArrowRight size={14} /></button></form></div><div className="absolute bottom-8 right-10 hidden items-end gap-1 opacity-70 sm:flex" aria-hidden="true">{[18, 32, 52, 39, 70, 44, 62, 28, 48, 74, 40, 22].map((height, index) => <span key={index} className="w-1 rounded-full bg-primary" style={{ height }} />)}</div>
      </section>
      <section><div className="mb-5 flex items-end justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-muted-foreground">{t.moodSectionLabel}</p><h2 className="mt-2 text-xl font-bold">{t.moods}</h2></div><Waves className="text-primary" size={19} /></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{moods.map((mood) => <button type="button" key={mood.id} onClick={() => playTrack(tracks.find((track) => track.mood === mood.id) || tracks[0])} data-testid={`button-mood-${mood.id}`} className="group relative overflow-hidden rounded-2xl border border-border bg-secondary/45 p-4 text-left transition hover:-translate-y-0.5 hover:border-primary/40"><span className="mb-7 flex h-8 w-8 items-center justify-center rounded-full border border-border text-primary"><Radio size={15} /></span><p className="font-bold">{t.moodLabels[mood.id].title}</p><p className="mt-1 text-[11px] leading-4 text-muted-foreground">{t.moodLabels[mood.id].note}</p><span className="absolute -bottom-6 -right-4 h-20 w-20 rounded-full opacity-20 transition group-hover:scale-125" style={{ background: `hsl(${mood.color})` }} /></button>)}</div></section>
      <section><div className="mb-5 flex items-end justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-muted-foreground">{t.curatedSectionLabel}</p><h2 className="mt-2 text-xl font-bold">{t.forYou}</h2></div><Link href="/search" data-testid="link-see-all" className="flex items-center gap-1 text-xs font-bold text-primary">{t.seeAll}<ArrowRight size={14} /></Link></div><div className="grid grid-cols-2 gap-x-3 gap-y-7 sm:grid-cols-3 lg:grid-cols-5">{tracks.slice(0, 5).map((track) => <TrackCard key={track.id} track={track} />)}</div></section>
      <section><div className="mb-5 flex items-end justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-muted-foreground">{t.creatorFeedLabel}</p><h2 className="mt-2 text-xl font-bold">{t.creatorFeed}</h2><p className="mt-1 text-xs text-muted-foreground">{t.creatorFeedIntro}</p></div><Heart className="text-primary" size={19} /></div><div className="grid gap-4 lg:grid-cols-2">{creators.flatMap((creator) => creator.posts.map((post) => <article key={post.id} className="rounded-2xl border border-border bg-card/55 p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full text-sm font-extrabold text-background bg-primary">{creator.name.slice(0,1)}</span><div className="min-w-0 flex-1"><Link href={`/creator/${creator.id}`} className="font-bold hover:text-primary">{creator.name}</Link><p className="text-[10px] text-muted-foreground">{creator.genre} · {post.time}</p></div><button type="button" onClick={() => toggleFollow(creator.id)} className="rounded-full border border-border px-3 py-1.5 text-[10px] font-bold transition hover:border-primary/50">{followed.includes(creator.id) ? t.following : t.follow}</button></div><p className="mt-4 text-sm leading-6">{post.text}</p><div className="mt-4 flex items-center gap-5 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><Heart size={14} /> {post.likes}</span><span className="inline-flex items-center gap-1"><MessageCircle size={14} /> {post.comments}</span><span className="inline-flex items-center gap-1"><Share2 size={14} /> {t.share}</span></div></article>))}</div></section>
       <section><div className="mb-5 flex items-end justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-muted-foreground">{t.artistsSectionLabel}</p><h2 className="mt-2 text-xl font-bold">{t.artistsTitle}</h2></div><Headphones className="text-primary" size={19} /></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{artists.map((artist, index) => <button type="button" key={artist.name} onClick={() => playTrack(tracks[index])} className="flex items-center gap-3 rounded-2xl border border-border bg-card/45 p-3 text-left transition hover:-translate-y-0.5 hover:border-primary/40" data-testid={`button-artist-${artist.name.toLowerCase()}`}><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full text-sm font-extrabold text-background" style={{ background: `hsl(${tracks[index].colors[0]})` }}>{artist.name.slice(0, 1)}</span><span className="min-w-0"><span className="block truncate text-sm font-bold">{artist.name}</span><span className="mt-1 block truncate text-[10px] text-muted-foreground">{t.genreNames[artist.genre]} · {artist.demoCount} {t.demoCount}</span></span></button>)}</div></section>
       <section className="grid gap-8 pb-4 lg:grid-cols-[1.1fr_.9fr]"><div><div className="mb-4 flex items-center justify-between"><div><p className="font-mono-ui text-[10px] uppercase tracking-[.2em] text-muted-foreground">{t.rotationSectionLabel}</p><h2 className="mt-2 text-xl font-bold">{t.fresh}</h2></div><Headphones size={19} className="text-primary" /></div><div className="rounded-2xl border border-border bg-card/50 p-2">{tracks.slice(5).map((track, index) => <TrackRow key={track.id} track={track} index={index} />)}</div></div><div className="flex min-h-[240px] flex-col justify-between overflow-hidden rounded-2xl border border-primary/25 bg-primary/10 p-6"><Sparkles className="text-primary" size={20} /><div><p className="font-mono-ui text-[10px] uppercase tracking-[.18em] text-primary">{t.createTitle}</p><h3 className="mt-3 max-w-xs text-2xl font-bold leading-tight">{t.createCopy}</h3><Link href="/create" data-testid="link-create-teaser" className="mt-5 inline-flex items-center gap-2 text-xs font-extrabold text-primary">{t.moreDetails} <ArrowRight size={14} /></Link></div></div></section>
    </div>
  </div>;
}